MAINT: update hv status dashboard
stfc/cloud-grafana-dashboards pull request #45
Opened 2024-02-28 16:36 UTC by anish-mudaraddi

previously it was printing a metric for each HV which was quite large and caused bugs when switching between prod and dev. Made it into a table instead

2024-02-29 10:51 UTC, khalford requested changes
Could you change the column alignment to centre. So the hv name and cpu count are closer together?

2024-02-29 11:00 UTC, khalford commented
Additionally, if you add an override to the cpu available field and set the cell type to gauge you get some cool bars

2024-02-29 12:00 UTC, khalford requested changes
Looks good. Only thing is to swap the threshold colours. So it turns green above 80 and red below. Since right now if more than 80 cores are available it shows red when it should be green

2024-02-29 14:04 UTC, khalford approved these changes
LGTM

2024-03-04 10:20 UTC, Protabs approved these changes

2024-03-04 10:37 UTC, merged