MAINT: Added different folders to help navigate.
stfc/cloud-grafana-dashboards pull request #46
Opened 2024-03-05 10:39 UTC by khalford

Using these generic folders it can help direct someone to find the information they are interested in.

### Description:

### Additional Notes

---

### Submitter:

Have you:

* [ ] Checked the latest commit runs on a Grafana instance using the aq personality `openstack-grafana`?
  
* [ ] Dashboards have clearly labelled panels, and are easy to read?

### Reviewer:

As part of reviewing this PR the changes must be tested on a Grafana instance. To do this:

* [ ] Spin up a machine with the aq personality `openstack-grafana`

* [ ] In `/etc/grafana/grafana.ini` under `[server]` comment out: domain, root_url, http_addr. Restart Grafana

* [ ] Open Grafana and navigate to browse dashboard

* [ ] You should see the dashboards which are from this repo

* [ ] Import any dashboards that have been added or modified in this PR to Grafana.
  
Have you:

* [ ] Checked whether the panels are clear and easy to read?

2024-03-05 16:10 UTC, DavidFair requested changes

2024-03-05 16:18 UTC, DavidFair approved these changes
LGTM, and a nice tidy up too

2024-03-06 14:48 UTC, anish-mudaraddi requested changes
Nit:  I can see two kiosk folders
![image](https://github.com/stfc/cloud-grafana-dashboards/assets/81758831/0b7fe6b9-d015-4179-93ec-08d743948315)

NIT: also can you change the folder name to Hypervisor instead of HyperVisor

2024-03-06 15:38 UTC, anish-mudaraddi approved these changes

2024-03-06 15:38 UTC, merged